

const products = [
    {
        _id: '1',
        name: 'coffee mugs',
        image: '/images/1.jpg',
        description: 'coffee mug',
        brand: 'homegoods',
        category: 'home products',
        price: 29.99,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        _id: '2',
        name: 'face wash',
        image: '/images/bottle.jpg',
        description: 'face wash',
        brand: 'homemade',
        category: 'beauty',
        price: 10.99,
        countInStock: 6,
        rating: 3,
        numReviews: 8,
    },
    {
        _id: '3',
        name: 'handmade bracelet',
        image: '/images/bracelets.jpg',
        description: 'friendship bracelet',
        brand: 'homemade',
        category: 'jewelry',
        price: 15.00,
        countInStock: 6,
        rating: 4,
        numReviews: 8,
    },
    {
        _id: '4',
        name: 'hand lotion',
        image: '/images/images1.jpg',
        description: 'lotion',
        brand: 'homemade',
        category: 'beauty',
        price: 10.00,
        countInStock: 6,
        rating: 5,
        numReviews: 8,
    },
    {
        _id: '5',
        name: 'eco-friendly razor',
        image: '/images/razor.jpg',
        description: 'razor',
        brand: 'homemade',
        category: 'beauty',
        price: 15.00,
        countInStock: 6,
        rating: 4,
        numReviews: 8,
    },
    {
        _id: '6',
        name: 'watch',
        image: '/images/watch.jpg',
        description: 'watch',
        brand: 'electronic',
        category: 'electronics',
        price: 30.00,
        countInStock: 6,
        rating: 2,
        numReviews: 8,
    },
]

export default products
